export enum TransportOrderStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  LOADING = 'LOADING',
  UNLOADING = 'UNLOADING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  PROBLEM = 'PROBLEM',
}
