export enum TransportOrderEventType {
  STATUS_CHANGED = 'STATUS_CHANGED',
  INCIDENT_DETOUR = 'INCIDENT_DETOUR',
  INCIDENT_ACCIDENT = 'INCIDENT_ACCIDENT',
  INCIDENT_DELAY = 'INCIDENT_DELAY',
  ROUTE_PAUSED = 'ROUTE_PAUSED',
  ROUTE_RESUMED = 'ROUTE_RESUMED',
  ROUTE_FINISHED = 'ROUTE_FINISHED',
  PROBLEM_REPORTED = 'PROBLEM_REPORTED',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
}
